//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Lexer_Parser/Parser/BubblGum.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BubblGumParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IBubblGumListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] BubblGumParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] BubblGumParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.define_stock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefine_stock([NotNull] BubblGumParser.Define_stockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.define_stock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefine_stock([NotNull] BubblGumParser.Define_stockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.chew_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChew_import([NotNull] BubblGumParser.Chew_importContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.chew_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChew_import([NotNull] BubblGumParser.Chew_importContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass([NotNull] BubblGumParser.ClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass([NotNull] BubblGumParser.ClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterface([NotNull] BubblGumParser.InterfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterface([NotNull] BubblGumParser.InterfaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.interface_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterface_member([NotNull] BubblGumParser.Interface_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.interface_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterface_member([NotNull] BubblGumParser.Interface_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.class_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_member([NotNull] BubblGumParser.Class_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.class_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_member([NotNull] BubblGumParser.Class_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibility([NotNull] BubblGumParser.VisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibility([NotNull] BubblGumParser.VisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct([NotNull] BubblGumParser.StructContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct([NotNull] BubblGumParser.StructContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] BubblGumParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] BubblGumParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.function_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_header([NotNull] BubblGumParser.Function_headerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.function_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_header([NotNull] BubblGumParser.Function_headerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] BubblGumParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] BubblGumParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.outputs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputs([NotNull] BubblGumParser.OutputsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.outputs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputs([NotNull] BubblGumParser.OutputsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.scope_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScope_body([NotNull] BubblGumParser.Scope_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.scope_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScope_body([NotNull] BubblGumParser.Scope_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_list([NotNull] BubblGumParser.Statement_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_list([NotNull] BubblGumParser.Statement_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] BubblGumParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] BubblGumParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.single_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_statement([NotNull] BubblGumParser.Single_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.single_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_statement([NotNull] BubblGumParser.Single_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.print_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint_statement([NotNull] BubblGumParser.Print_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.print_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint_statement([NotNull] BubblGumParser.Print_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.debug_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDebug_statement([NotNull] BubblGumParser.Debug_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.debug_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDebug_statement([NotNull] BubblGumParser.Debug_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.base_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase_statement([NotNull] BubblGumParser.Base_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.base_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase_statement([NotNull] BubblGumParser.Base_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_statement([NotNull] BubblGumParser.Return_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_statement([NotNull] BubblGumParser.Return_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.primitive_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitive_declaration([NotNull] BubblGumParser.Primitive_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.primitive_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitive_declaration([NotNull] BubblGumParser.Primitive_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] BubblGumParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] BubblGumParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.variable_inc_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_inc_dec([NotNull] BubblGumParser.Variable_inc_decContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.variable_inc_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_inc_dec([NotNull] BubblGumParser.Variable_inc_decContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] BubblGumParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] BubblGumParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.elif_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElif_statement([NotNull] BubblGumParser.Elif_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.elif_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElif_statement([NotNull] BubblGumParser.Elif_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_statement([NotNull] BubblGumParser.Else_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_statement([NotNull] BubblGumParser.Else_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoop([NotNull] BubblGumParser.LoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoop([NotNull] BubblGumParser.LoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_loop([NotNull] BubblGumParser.While_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_loop([NotNull] BubblGumParser.While_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.repeat_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeat_loop([NotNull] BubblGumParser.Repeat_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.repeat_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeat_loop([NotNull] BubblGumParser.Repeat_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.pop_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPop_loop([NotNull] BubblGumParser.Pop_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.pop_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPop_loop([NotNull] BubblGumParser.Pop_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] BubblGumParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] BubblGumParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.double"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDouble([NotNull] BubblGumParser.DoubleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.double"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDouble([NotNull] BubblGumParser.DoubleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt([NotNull] BubblGumParser.IntContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt([NotNull] BubblGumParser.IntContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] BubblGumParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] BubblGumParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] BubblGumParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] BubblGumParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] BubblGumParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] BubblGumParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] BubblGumParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] BubblGumParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.primitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitive([NotNull] BubblGumParser.PrimitiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.primitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitive([NotNull] BubblGumParser.PrimitiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple([NotNull] BubblGumParser.TupleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple([NotNull] BubblGumParser.TupleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.primitive_pack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitive_pack([NotNull] BubblGumParser.Primitive_packContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.primitive_pack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitive_pack([NotNull] BubblGumParser.Primitive_packContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.any_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny_array([NotNull] BubblGumParser.Any_arrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.any_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny_array([NotNull] BubblGumParser.Any_arrayContext context);
}
