//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Lexer_Parser/Parser/BubblGum.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBubblGumListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class BubblGumBaseListener : IBubblGumListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] BubblGumParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] BubblGumParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.define_stock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefine_stock([NotNull] BubblGumParser.Define_stockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.define_stock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefine_stock([NotNull] BubblGumParser.Define_stockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass([NotNull] BubblGumParser.ClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass([NotNull] BubblGumParser.ClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface([NotNull] BubblGumParser.InterfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface([NotNull] BubblGumParser.InterfaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.interface_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface_member([NotNull] BubblGumParser.Interface_memberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.interface_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface_member([NotNull] BubblGumParser.Interface_memberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.class_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_member([NotNull] BubblGumParser.Class_memberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.class_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_member([NotNull] BubblGumParser.Class_memberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVisibility([NotNull] BubblGumParser.VisibilityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVisibility([NotNull] BubblGumParser.VisibilityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.struct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct([NotNull] BubblGumParser.StructContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.struct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct([NotNull] BubblGumParser.StructContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] BubblGumParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] BubblGumParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.function_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_header([NotNull] BubblGumParser.Function_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.function_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_header([NotNull] BubblGumParser.Function_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] BubblGumParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] BubblGumParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.outputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputs([NotNull] BubblGumParser.OutputsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.outputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputs([NotNull] BubblGumParser.OutputsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.scope_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScope_body([NotNull] BubblGumParser.Scope_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.scope_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScope_body([NotNull] BubblGumParser.Scope_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement_list([NotNull] BubblGumParser.Statement_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement_list([NotNull] BubblGumParser.Statement_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] BubblGumParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] BubblGumParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.single_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_statement([NotNull] BubblGumParser.Single_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.single_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_statement([NotNull] BubblGumParser.Single_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.chew_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChew_statement([NotNull] BubblGumParser.Chew_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.chew_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChew_statement([NotNull] BubblGumParser.Chew_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.print_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_statement([NotNull] BubblGumParser.Print_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.print_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_statement([NotNull] BubblGumParser.Print_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.debug_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDebug_statement([NotNull] BubblGumParser.Debug_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.debug_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDebug_statement([NotNull] BubblGumParser.Debug_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.base_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBase_statement([NotNull] BubblGumParser.Base_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.base_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBase_statement([NotNull] BubblGumParser.Base_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] BubblGumParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] BubblGumParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.primitive_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitive_declaration([NotNull] BubblGumParser.Primitive_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.primitive_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitive_declaration([NotNull] BubblGumParser.Primitive_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] BubblGumParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] BubblGumParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.variable_inc_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_inc_dec([NotNull] BubblGumParser.Variable_inc_decContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.variable_inc_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_inc_dec([NotNull] BubblGumParser.Variable_inc_decContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] BubblGumParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] BubblGumParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.elif_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElif_statement([NotNull] BubblGumParser.Elif_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.elif_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElif_statement([NotNull] BubblGumParser.Elif_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.else_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_statement([NotNull] BubblGumParser.Else_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.else_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_statement([NotNull] BubblGumParser.Else_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop([NotNull] BubblGumParser.LoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop([NotNull] BubblGumParser.LoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.while_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_loop([NotNull] BubblGumParser.While_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.while_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_loop([NotNull] BubblGumParser.While_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.repeat_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeat_loop([NotNull] BubblGumParser.Repeat_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.repeat_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeat_loop([NotNull] BubblGumParser.Repeat_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.pop_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPop_loop([NotNull] BubblGumParser.Pop_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.pop_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPop_loop([NotNull] BubblGumParser.Pop_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] BubblGumParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] BubblGumParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.double"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDouble([NotNull] BubblGumParser.DoubleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.double"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDouble([NotNull] BubblGumParser.DoubleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] BubblGumParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] BubblGumParser.IntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] BubblGumParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] BubblGumParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] BubblGumParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] BubblGumParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] BubblGumParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] BubblGumParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] BubblGumParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] BubblGumParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.primitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitive([NotNull] BubblGumParser.PrimitiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.primitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitive([NotNull] BubblGumParser.PrimitiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.tuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTuple([NotNull] BubblGumParser.TupleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.tuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTuple([NotNull] BubblGumParser.TupleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.primitive_pack"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitive_pack([NotNull] BubblGumParser.Primitive_packContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.primitive_pack"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitive_pack([NotNull] BubblGumParser.Primitive_packContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.any_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAny_array([NotNull] BubblGumParser.Any_arrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.any_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAny_array([NotNull] BubblGumParser.Any_arrayContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
