//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./AntlrCSharp/Parser/BubblGum.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBubblGumListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class BubblGumBaseListener : IBubblGumListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] BubblGumParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] BubblGumParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass([NotNull] BubblGumParser.ClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass([NotNull] BubblGumParser.ClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.class_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_member([NotNull] BubblGumParser.Class_memberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.class_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_member([NotNull] BubblGumParser.Class_memberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVisibility([NotNull] BubblGumParser.VisibilityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVisibility([NotNull] BubblGumParser.VisibilityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] BubblGumParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] BubblGumParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.function_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_header([NotNull] BubblGumParser.Function_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.function_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_header([NotNull] BubblGumParser.Function_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.constructor_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructor_header([NotNull] BubblGumParser.Constructor_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.constructor_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructor_header([NotNull] BubblGumParser.Constructor_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] BubblGumParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] BubblGumParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.outputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputs([NotNull] BubblGumParser.OutputsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.outputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputs([NotNull] BubblGumParser.OutputsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.single_output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_output([NotNull] BubblGumParser.Single_outputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.single_output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_output([NotNull] BubblGumParser.Single_outputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] BubblGumParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] BubblGumParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop([NotNull] BubblGumParser.LoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop([NotNull] BubblGumParser.LoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.while_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_loop([NotNull] BubblGumParser.While_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.while_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_loop([NotNull] BubblGumParser.While_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.repeat_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeat_loop([NotNull] BubblGumParser.Repeat_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.repeat_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeat_loop([NotNull] BubblGumParser.Repeat_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.pop_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPop_loop([NotNull] BubblGumParser.Pop_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.pop_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPop_loop([NotNull] BubblGumParser.Pop_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.scope_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScope_body([NotNull] BubblGumParser.Scope_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.scope_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScope_body([NotNull] BubblGumParser.Scope_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] BubblGumParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] BubblGumParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.print_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_statement([NotNull] BubblGumParser.Print_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.print_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_statement([NotNull] BubblGumParser.Print_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.debug_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDebug_statement([NotNull] BubblGumParser.Debug_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.debug_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDebug_statement([NotNull] BubblGumParser.Debug_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.base_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBase_statement([NotNull] BubblGumParser.Base_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.base_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBase_statement([NotNull] BubblGumParser.Base_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] BubblGumParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] BubblGumParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.variable_declaration_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declaration_assignment([NotNull] BubblGumParser.Variable_declaration_assignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.variable_declaration_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declaration_assignment([NotNull] BubblGumParser.Variable_declaration_assignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declaration([NotNull] BubblGumParser.Variable_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declaration([NotNull] BubblGumParser.Variable_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.variable_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_assignment([NotNull] BubblGumParser.Variable_assignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.variable_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_assignment([NotNull] BubblGumParser.Variable_assignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] BubblGumParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] BubblGumParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] BubblGumParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] BubblGumParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.innerCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInnerCondition([NotNull] BubblGumParser.InnerConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.innerCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInnerCondition([NotNull] BubblGumParser.InnerConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.unaryCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryCondition([NotNull] BubblGumParser.UnaryConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.unaryCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryCondition([NotNull] BubblGumParser.UnaryConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] BubblGumParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] BubblGumParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.bin_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBin_op([NotNull] BubblGumParser.Bin_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.bin_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBin_op([NotNull] BubblGumParser.Bin_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.mathOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathOperation([NotNull] BubblGumParser.MathOperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.mathOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathOperation([NotNull] BubblGumParser.MathOperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.mathOperationTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathOperationTerm([NotNull] BubblGumParser.MathOperationTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.mathOperationTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathOperationTerm([NotNull] BubblGumParser.MathOperationTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.mathOperationFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathOperationFactor([NotNull] BubblGumParser.MathOperationFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.mathOperationFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathOperationFactor([NotNull] BubblGumParser.MathOperationFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.mathOperationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathOperationUnit([NotNull] BubblGumParser.MathOperationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.mathOperationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathOperationUnit([NotNull] BubblGumParser.MathOperationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] BubblGumParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] BubblGumParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] BubblGumParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] BubblGumParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] BubblGumParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] BubblGumParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] BubblGumParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] BubblGumParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.primitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitive([NotNull] BubblGumParser.PrimitiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.primitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitive([NotNull] BubblGumParser.PrimitiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumParser.primitive_pack"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitive_pack([NotNull] BubblGumParser.Primitive_packContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumParser.primitive_pack"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitive_pack([NotNull] BubblGumParser.Primitive_packContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
