//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Preprocessing/Parser/BubblGumHeader.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BubblGumHeaderParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IBubblGumHeaderListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumHeaderParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] BubblGumHeaderParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumHeaderParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] BubblGumHeaderParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumHeaderParser.define_stock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefine_stock([NotNull] BubblGumHeaderParser.Define_stockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumHeaderParser.define_stock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefine_stock([NotNull] BubblGumHeaderParser.Define_stockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BubblGumHeaderParser.chew_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChew_import([NotNull] BubblGumHeaderParser.Chew_importContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BubblGumHeaderParser.chew_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChew_import([NotNull] BubblGumHeaderParser.Chew_importContext context);
}
